import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  hero: {
    title: "My Projects",
    tagline: "Pioneering innovation through practical software design",
    heading: "Project Showcase",
    description:
      "A selection of my top projects combining AI, automation, 3D simulation, and secure web technology — all developed with modern frameworks and advanced system architecture.",
  },
  projects: [
    {
      title: "AI Chatbot Intelligent Conversational Assistant",
      shortTitle: "IntelliChat",
      description: `An advanced conversational AI assistant built using Python and TensorFlow, capable of understanding context and intent via transformer-based NLP models. The system features a responsive React Native frontend styled with TailwindCSS, offering smooth conversational experiences. Integrated with OpenAI API and Hugging Face models, it supports translation, summarization, and creative writing tasks. Node.js and Express handle authentication (JWT), MongoDB manages persistent chat data, and Docker ensures scalable deployments. Tested thoroughly with Postman and developed in VS Code for multi-platform consistency.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "React Native" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "MongoDB" },
        { name: "OpenAI API" },
        { name: "TailwindCSS" },
        { name: "Docker" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    {
      title: "Voxa – Futuristic Robotics Innovation Platform",
      shortTitle: "Voxa",
      description: `Voxa is a groundbreaking platform for designing and deploying advanced robotics solutions, blending AI intelligence with immersive 3D simulations to build the future one robot at a time. Developed with Next.js and TailwindCSS for a sleek, dark futuristic interface, it integrates Three.js and Framer Motion for dynamic robot visualizations. Backend powered by Python, TensorFlow, and FastAPI enables AI-driven control systems and predictive behaviors. Robotics simulation leverages Unity and ROS, with Blender for high-fidelity asset modeling. Deployed on AWS using Docker for global scalability, with Postman for API testing and collaborative development via GitHub.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "Nextjs" },
        { name: "TailwindCSS" },
        { name: "Framer Motion" },
        { name: "Threejs" },
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "FastAPI" },
        { name: "Unity" },
        { name: "ROS" },
        { name: "Blender" },
        { name: "AWS" },
        { name: "Docker" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    {
      title: "Veon AI – Intelligent Automation and Decision Platform",
      shortTitle: "Veon AI",
      description: `Veon AI is a next-gen automation platform that merges intelligent agents, predictive analytics, and conversational systems to enhance business decision-making. Built with React and TailwindCSS, it offers an elegant and dynamic interface featuring multiple AI-driven modules such as Analytics Agent, Predictive Agent, and Smart Automation. Backend AI logic is powered by Python, TensorFlow, and FastAPI for real-time inference, while Node.js and Express handle system orchestration. The project emphasizes security via JWT, containerized deployment through Docker, and scalable cloud hosting on AWS. Postman testing ensures API robustness and reliability across environments.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "FastAPI" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
        { name: "JWT" },
      ],
    },
    {
      title: "HyperChain – AI-Powered Blockchain Security System",
      shortTitle: "HyperChain",
      description: `HyperChain is a cutting-edge blockchain ecosystem enhanced with AI-powered verification and security modules. Built using React, TailwindCSS, and Node.js, it delivers a sleek, futuristic web experience inspired by decentralized technologies. Python-based TensorFlow models are used to predict and prevent fraudulent transactions in real time. Smart contracts are managed through Solidity and deployed on Ethereum, ensuring transparency and scalability. The backend, orchestrated with Express and FastAPI, communicates with blockchain nodes via secure APIs tested through Postman. Deployed using Docker containers on AWS and Azure, HyperChain ensures 99.9% uptime, unmatched transaction speed, and AI-driven threat intelligence for enterprise blockchain networks.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "FastAPI" },
        { name: "Blockchain" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "Azure" },
        { name: "Postman" },
        { name: "GitHub" },
      ],
    },
    // NEW PROJECT: CyberPunk
    {
      title: "CyberPunk – Dystopian AI Storytelling Engine",
      shortTitle: "CyberPunk",
      description: `A futuristic AI-powered storytelling platform set in a cyberpunk universe. Users explore immersive narratives, generate dynamic lore, and interact with AI characters in a high-tech, low-life dystopia. Built with React and Three.js for 3D visuals, animated with Framer Motion, and styled using TailwindCSS. The backend uses Python and FastAPI to power procedural story generation via OpenAI API. 3D assets are crafted in Blender, UI/UX designed in Figma. Fully containerized with Docker and deployed on AWS for global scalability. The platform blurs the line between humanity and machinery through interactive events and evolving world lore.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "Threejs" },
        { name: "Framer Motion" },
        { name: "TailwindCSS" },
        { name: "Python" },
        { name: "FastAPI" },
        { name: "OpenAI API" },
        { name: "Blender" },
        { name: "Figma" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
      ],
    },
    // NEW PROJECT: Chainex
    {
      title: "Chainex – Advanced Cryptocurrency Trading Dashboard",
      shortTitle: "Chainex",
      description: `Chainex is a comprehensive cryptocurrency trading and analytics dashboard that provides real-time market insights, portfolio tracking, and automated trading tools. Built with React for a dynamic, responsive UI and TailwindCSS for sleek styling, it integrates live data from exchanges like Binance and KuCoin. Backend services leverage Node.js and Express for API orchestration, with Python and FastAPI handling advanced analytics, fear/greed indexing, and transaction monitoring. Blockchain integration ensures secure wallet connections and transaction history. Deployed via Docker on AWS for high availability, with Postman for API validation and GitHub for collaborative development.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "Python" },
        { name: "FastAPI" },
        { name: "Blockchain" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    // NEW PROJECT: ShipX
    {
      title: "ShipX – Intelligent Logistics Management Platform",
      shortTitle: "ShipX",
      description: `ShipX is a powerful logistics dashboard that empowers users to track shipments, monitor vehicles, analyze data, and connect with clients in real-time. Developed with React for an intuitive and responsive interface, styled with TailwindCSS for a modern dark-themed design. Backend orchestration uses Node.js and Express to handle shipment statistics, client interactions, and vehicle activity feeds. Python and FastAPI drive advanced analytics for predictive insights and reporting. Integrated MongoDB for data persistence, with Docker for containerized deployment on AWS ensuring seamless scalability. Postman validates APIs, and Figma refines the user-centric UI/UX experience.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "Python" },
        { name: "FastAPI" },
        { name: "MongoDB" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "Figma" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    // NEW PROJECT: Mori
    {
      title: "Mori – Futurism Meets Functionality Platform",
      shortTitle: "Mori",
      description: `Mori is a visionary cutting-edge platform where futurism meets functionality, enabling seamless deployment of AI models with visionary design and optimal performance. Built with React and TailwindCSS for a vibrant, immersive interface, it features dynamic 3D elements via Three.js and smooth animations with Framer Motion. Backend powered by Python, FastAPI, and OpenAI API handles AI model orchestration, cost reduction analytics, and uptime guarantees. Blender crafts custom 3D assets, while Docker and AWS ensure scalable, high-availability deployments. Postman tests APIs rigorously, with GitHub facilitating collaborative innovation.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Threejs" },
        { name: "Framer Motion" },
        { name: "Python" },
        { name: "FastAPI" },
        { name: "OpenAI API" },
        { name: "Blender" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    // NEW PROJECT: MedPro
    {
      title: "MedPro – Modern Medical Marketing Solutions",
      shortTitle: "MedPro",
      description: `MedPro is a new-age marketing platform tailored for medical practices, offering comprehensive solutions in social media management, SEO, Google traffic generation, and online reviews to drive patient engagement and growth. Developed with React for a clean, professional interface and TailwindCSS for responsive blue-themed styling. Backend utilizes Node.js and Express for service orchestration, with MongoDB for secure data handling of client campaigns and analytics. Integrated with Docker for seamless deployments on AWS, ensuring HIPAA-compliant scalability. Postman validates APIs, Figma designs user-friendly dashboards, and GitHub supports team collaboration.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "MongoDB" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "Figma" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    // NEW PROJECT: Health Services
    {
      title: "HealthPro – Advanced Healthcare Marketing Platform",
      shortTitle: "HealthPro",
      description: `HealthPro is an innovative marketing solution dedicated to empowering modern medical practices with cutting-edge digital strategies, including social media optimization, SEO enhancement, targeted Google traffic, and streamlined online review management. Crafted with React for intuitive user interfaces and TailwindCSS for vibrant, healthcare-themed designs. The backend, built on Node.js and Express, integrates MongoDB for robust data management and analytics tracking. Docker enables efficient, secure deployments on AWS, prioritizing compliance and performance. Figma prototypes user flows, Postman ensures API integrity, and GitHub fosters collaborative development.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "MongoDB" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "Figma" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    // NEW PROJECT: NeuroNet – AI & ML Model Training Dashboard
    {
      title: "NeuroNet – Advanced AI & ML Model Training Platform",
      shortTitle: "NeuroNet",
      description: `NeuroNet is a cutting-edge dashboard for training, fine-tuning, and deploying AI & ML models at scale, featuring real-time monitoring of neural network performance, hyperparameter optimization, and dataset visualization. Built with React for an interactive UI and TailwindCSS for modern styling, it supports frameworks like TensorFlow and PyTorch for seamless model experimentation. Backend powered by Python and FastAPI handles distributed training jobs, with OpenAI API integration for generative tasks. Features include accuracy/loss charts, confusion matrices, and automated model selection. Deployed on AWS with Docker for scalability, tested via Postman, and collaborated on GitHub.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "PyTorch" },
        { name: "FastAPI" },
        { name: "OpenAI API" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    // NEW PROJECT: Chainex AI – Intelligent Crypto Investment Dashboard
    {
      title: "Chainex AI – AI-Powered Crypto Investment and Analytics Platform",
      shortTitle: "Chainex AI",
      description: `Chainex AI is an intelligent dashboard blending crypto trading with AI-driven insights, featuring personalized offers, AI Bot for automated advice, real-time portfolio tracking (e.g., BTC at $1.2M, ETH at 460K, SOL at 290K), and performance statistics with buy/sell signals. Built with React for a dynamic UI and TailwindCSS for sleek, modern design, it includes blog, invest, news sections, and newsletter subscriptions. Backend leverages Python, TensorFlow for predictive analytics and market forecasting, FastAPI for API handling, and OpenAI API for the AI Bot. Blockchain integration for secure wallet views, deployed on AWS with Docker, tested via Postman, and developed collaboratively on GitHub.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "FastAPI" },
        { name: "OpenAI API" },
        { name: "Blockchain" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
  ],
};
const projectsSlice = createSlice({
  name: "projects",
  initialState,
  reducers: {},
});
export default projectsSlice.reducer;