import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  hero: {
    title: "My Projects",
    tagline: "Pioneering innovation through practical software design",
    heading: "Project Showcase",
    description:
      "A selection of my top projects combining AI, automation, 3D simulation, and secure web technology — all developed with modern frameworks and advanced system architecture.",
  },
  projects: [
    {
      title: "AI Chatbot Intelligent Conversational Assistant",
      shortTitle: "IntelliChat",
      description: `An advanced conversational AI assistant built using Python and TensorFlow, capable of understanding context and intent via transformer-based NLP models. The system features a responsive React Native frontend styled with TailwindCSS, offering smooth conversational experiences. Integrated with OpenAI API and Hugging Face models, it supports translation, summarization, and creative writing tasks. Node.js and Express handle authentication (JWT), MongoDB manages persistent chat data, and Docker ensures scalable deployments. Tested thoroughly with Postman and developed in VS Code for multi-platform consistency.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "React Native" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "MongoDB" },
        { name: "OpenAI API" },
        { name: "TailwindCSS" },
        { name: "Docker" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    {
      title: "BIONE Futuristic AI Innovation Platform",
      shortTitle: "BIONE",
      description: `BIONE is a futuristic AI research and visualization platform developed with Next.js and TailwindCSS, designed to demonstrate real-time computer vision and robotics intelligence. It integrates TensorFlow and OpenCV for visual analytics, while ROS and Unity handle robotics simulation and motion systems. Flask and FastAPI power modular microservices that handle AI inference and data analysis. The frontend integrates Three.js and Framer Motion for stunning 3D animations. Cloud deployment across AWS, Google Cloud, and Azure ensures high scalability and reliability, with Docker and Postman used for seamless CI/CD workflows.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "Nextjs" },
        { name: "TailwindCSS" },
        { name: "Framer Motion" },
        { name: "Threejs" },
        { name: "Python" },
        { name: "Flask" },
        { name: "FastAPI" },
        { name: "TensorFlow" },
        { name: "PyTorch" },
        { name: "OpenCV" },
        { name: "ROS" },
        { name: "Blender" },
        { name: "Unity" },
        { name: "AWS" },
        { name: "Google Cloud" },
        { name: "Azure" },
        { name: "Docker" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
      ],
    },
    {
      title: "Veon AI – Intelligent Automation and Decision Platform",
      shortTitle: "Veon AI",
      description: `Veon AI is a next-gen automation platform that merges intelligent agents, predictive analytics, and conversational systems to enhance business decision-making. Built with React and TailwindCSS, it offers an elegant and dynamic interface featuring multiple AI-driven modules such as Analytics Agent, Predictive Agent, and Smart Automation. Backend AI logic is powered by Python, TensorFlow, and FastAPI for real-time inference, while Node.js and Express handle system orchestration. The project emphasizes security via JWT, containerized deployment through Docker, and scalable cloud hosting on AWS. Postman testing ensures API robustness and reliability across environments.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "FastAPI" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
        { name: "Postman" },
        { name: "JWT" },
      ],
    },
    {
      title: "HyperChain – AI-Powered Blockchain Security System",
      shortTitle: "HyperChain",
      description: `HyperChain is a cutting-edge blockchain ecosystem enhanced with AI-powered verification and security modules. Built using React, TailwindCSS, and Node.js, it delivers a sleek, futuristic web experience inspired by decentralized technologies. Python-based TensorFlow models are used to predict and prevent fraudulent transactions in real time. Smart contracts are managed through Solidity and deployed on Ethereum, ensuring transparency and scalability. The backend, orchestrated with Express and FastAPI, communicates with blockchain nodes via secure APIs tested through Postman. Deployed using Docker containers on AWS and Azure, HyperChain ensures 99.9% uptime, unmatched transaction speed, and AI-driven threat intelligence for enterprise blockchain networks.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "TailwindCSS" },
        { name: "Node.js" },
        { name: "Express" },
        { name: "Python" },
        { name: "TensorFlow" },
        { name: "FastAPI" },
        { name: "Blockchain" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "Azure" },
        { name: "Postman" },
        { name: "GitHub" },
      ],
    },
    // NEW PROJECT: CyberPunk
    {
      title: "CyberPunk – Dystopian AI Storytelling Engine",
      shortTitle: "CyberPunk",
      description: `A futuristic AI-powered storytelling platform set in a cyberpunk universe. Users explore immersive narratives, generate dynamic lore, and interact with AI characters in a high-tech, low-life dystopia. Built with React and Three.js for 3D visuals, animated with Framer Motion, and styled using TailwindCSS. The backend uses Python and FastAPI to power procedural story generation via OpenAI API. 3D assets are crafted in Blender, UI/UX designed in Figma. Fully containerized with Docker and deployed on AWS for global scalability. The platform blurs the line between humanity and machinery through interactive events and evolving world lore.`,
      toolsHeading: "Key Tools & Technologies",
      tools: [
        { name: "React" },
        { name: "Threejs" },
        { name: "Framer Motion" },
        { name: "TailwindCSS" },
        { name: "Python" },
        { name: "FastAPI" },
        { name: "OpenAI API" },
        { name: "Blender" },
        { name: "Figma" },
        { name: "Docker" },
        { name: "AWS" },
        { name: "GitHub" },
        { name: "VS Code" },
      ],
    },
  ],
};

const projectsSlice = createSlice({
  name: "projects",
  initialState,
  reducers: {},
});

export default projectsSlice.reducer;